#!/bin/bash
set -e

# The `postrm` script can be called in different ways
# $1 will be "remove" or "purge"
case "$1" in
    remove|purge)
        # On remove or purge, disable the service if systemd is running
        if [ -d /run/systemd/system ]; then
            echo "Disabling libra service..."
            systemctl disable libra.service >/dev/null 2>&1 || true
        fi

        echo "Removing symbolic link for libphidget22..."
        rm -f /usr/lib/libphidget22.so

        echo "Reloading udev rules..."
        udevadm control --reload-rules
        udevadm trigger
    ;;
esac

exit 0